# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('item_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('item_description', models.CharField(blank=True, max_length=200)),
                ('item_price', models.PositiveIntegerField(db_index=True, verbose_name='price')),
                ('item_quantity', models.PositiveIntegerField(db_index=True, default=0, verbose_name='quantity')),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('threshold_quantity', models.PositiveIntegerField(default=5)),
                ('item_category', models.CharField(choices=[('ONE', 'category 1'), ('TWO', 'category 2'), ('THREE', 'category 3')], max_length=10)),
                ('gst', models.FloatField(choices=[(0, '0'), (5, '5'), (12, '12'), (18, '18'), (28, '28')], verbose_name='GST')),
            ],
        ),
    ]
