# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('mob_no', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_credit', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
